name: s3_storage_client
description: S3 Dart Client SDK that provides simple APIs to access any Amazon S3 API compatible object storage server.
version: 2025.12.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  http: ^1.6.0
  crypto: ^3.0.7
  convert: ^3.1.2
  xml: ^6.6.1
  buffer: ^1.2.3
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  html: ^0.15.6
